server:
  port: 8090

spring:
  application:
    name: authorization-service
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password: sa
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false

token:
  validity:
    refresh: 10
    access: 30
  issuer: Serggge