CREATE TABLE IF NOT EXISTS credentials
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login varchar(64) NOT NULL,
  password varchar(256) NOT NULL,
  active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS refresh_tokens
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credential_id bigint REFERENCES credentials(id) ON DELETE CASCADE,
  token varchar(256),
  expired_time timestamp,
  active boolean DEFAULT true
);