DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS public_keys;
DROP TABLE IF EXISTS ERRORS;

CREATE TABLE credentials
(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login varchar(64) NOT NULL,
  password varchar(256) NOT NULL,
  active boolean DEFAULT true
);

CREATE TABLE public_keys
(
   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   key_identifier varchar(1000),
   public_key varchar(10000),
   issuer varchar(64),
   active boolean DEFAULT true
);