CREATE SCHEMA IF NOT EXISTS public;
SET SCHEMA public;

CREATE TABLE IF NOT EXISTS roles(
    id bigint PRIMARY KEY,
    role_name varchar(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS credentials(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar(128) UNIQUE NOT NULL,
    password varchar(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name varchar(64) NOT NULL,
    first_name varchar(64) NOT NULL,
    surname varchar(64) DEFAULT '',
    birth_date date NOT NULL,
    email varchar(64) UNIQUE NOT NULL,
    phone_number varchar(64) NOT NULL,
    role_id bigint REFERENCES roles(id),
    credential_id bigint REFERENCES credentials(id)
);