CREATE SCHEMA IF NOT EXISTS public;
SET SCHEMA public;

CREATE TABLE IF NOT EXISTS roles
(
id bigint PRIMARY KEY,
name varchar(64) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
last_name varchar(64) NOT NULL,
first_name varchar(64) NOT NULL,
surname varchar(64),
birth_date date NOT NULL,
email varchar(64) UNIQUE NOT NULL,
phone_number varchar(64) NOT NULL,
role_id bigint REFERENCES roles (id)
);