DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_authorization;

CREATE TABLE IF NOT EXISTS users(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name varchar(64) NOT NULL,
    first_name varchar(64) NOT NULL,
    surname varchar(64) DEFAULT '',
    birth_date date NOT NULL,
    email varchar(64) UNIQUE NOT NULL,
    phone_number varchar(64) NOT NULL,
    active boolean DEFAULT true,
    auth_id bigint UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_authorization(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id bigint UNIQUE NOT NULL,
    user_id bigint REFERENCES users(id),
    active boolean DEFAULT true
);